### ISSUE TITLE
Leaderboard and Acheivements

### ISSUE THREAD

**Issue by Mr-Coxall** [MotherTeresaHS/FinalAppGroup2-2015#13]
If they are not logged into Game Center, then when they click on the 2 buttons, an alert should tell you you are not logged in, instead of just nothing.

**Comment by ZachariasOctavious** [comment]
I have added alerts so the user gets prompted if they're not logged into Game Center when the 2 buttons are pressed.

**Comment by Mr-Coxall** [comment]
Good
