### ISSUE TITLE
Use new icon

### ISSUE THREAD

**Issue by Mr-Coxall** [MotherTeresaHS/FinalAppGroup2-2015#14]
Use the new Icon1024 that is in dropbox, with the MT on the corner.

**Comment by Mr-Coxall** [comment]
Make sure it is used when you do the build in Codea

**Comment by ZachariasOctavious** [comment]
I've saved the Icon1024 and when I export the project I'll use it for the icon.

**Comment by Mr-Coxall** [comment]
Good
