### ISSUE TITLE
Candies

### ISSUE THREAD

**Issue by Mr-Coxall** [MotherTeresaHS/FinalAppGroup2-2015#16]
I get candies, but I can not see how many I have anywhere.
Should it be on the main menu?
Are the "candies" the equivalent of points?

So, ...
I have 425 candies and that is ny score?

**Comment by ZachariasOctavious** [comment]
The candy the user obtains is the currency used in the store. The candies are not equivalent to points. There is a variable for the amount of equations right which I can add to the main menu scene or anywhere else.

**Comment by ZachariasOctavious** [comment]
I've added the variable to the main menu scene above the lesdrtboards, store and achievements button. It may change locations and it is the official points system of the game.

**Comment by Mr-Coxall** [comment]
Ok
